version: "3.1"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app_development
      POSTGRES_PASSWORD: secret
    volumes:
      - hostedgpt_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app", "-d", "app_development"]
      interval: 1s
      retries: 5

  base: &base
    depends_on: ["postgres"]
    restart: on-failure:3
    tty: true
    build:
      context: .
      target: development
    environment:
      # Be sure to add environment variables to config/options.yml
      - DATABASE_URL=postgres://app:secret@postgres/app_development
      - DEV_HOST=${DEV_HOST:-localhost} # Set if you want to use a different hostname
      - OVERMIND_COLORS=2,3,5
      - VOICE_FEATURE
      - REGISTRATION_FEATURE
      - PASSWORD_AUTHENTICATION_FEATURE
      - GOOGLE_AUTHENTICATION_FEATURE
      - HTTP_HEADER_AUTHENTICATION_FEATURE
      - ALLOWED_REQUEST_ORIGINS
      - DEFAULT_LLM_KEYS_FEATURE
      - DEFAULT_OPENAI_KEY
      - DEFAULT_ANTHROPIC_KEY
      - DEFAULT_GROQ_KEY
      - GOOGLE_AUTH_CLIENT_ID
      - GOOGLE_AUTH_CLIENT_SECRET
      - HTTP_HEADER_AUTH_EMAIL
      - HTTP_HEADER_AUTH_NAME
      - HTTP_HEADER_AUTH_UID
      - CLOUDFLARE_STORAGE_FEATURE
      - CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET
      - POSTMARK_MAILER_FEATURE
      - POSTMARK_SERVER_API_TOKEN
      - POSTMARK_FROM_EMAIL
      - POSTMARK_PASSWORD_RESET_TEMPLATE_ALIAS
      - ACTION_MAILER_HOST
      - PRODUCT_NAME
    ports: ["3000:3000"]
    volumes:
      - .:/rails

volumes:
  hostedgpt_pgdata:
