blank_issues_enabled: false
contact_links:
  - name: DON'T POST ISSUES. Have a bug, feature idea, or any question? Start a discussion
    about: Please start Discussions for everything. Project maintainers will create issues.
    url: https://github.com/allyourbot/hostedgpt/discussions/new?category=general
